from pydantic import BaseModel,Field
from typing import Optional,List,Literal

class ChunkCitation(BaseModel):
    source : str = Field(... ,description="Name of the Pdf file the chunk has been extracted from")
    #section : Optional[str] = Field(None , description= 'Relevant section of hte source pdf')
    pg_no : Optional[int] = Field(None, description='Page number for the additional pdfs section')
    score : Optional[float] = Field(None,description='Similarity score of each chunk')
    chunk_id: Optional[int] = Field(None, description='Chunk id incase of risk_data')
    chunk_text: str = Field(...,description="Actual Text")


class RetrievedContext(BaseModel):
    question : str = Field(...,description="Question generated by llm based on compliance report")
    ass_chks = List[ChunkCitation] = Field(..., description='list of citaitons associated with the following question')


class ViolationFindings(BaseModel):
    violation :str = Field(...,description="short description on violation broken")
    severity: Literal['low','medium', 'high','critical'] = Field(..., description="Severirty of the broken violation")
    reasoning: str = Field(..., description='Explanationof why this is a violation based on the retrieved chunks')
    cited_chks_ids:str = Field(..., description="chunk_id/src of the chunks from the retrieved context that support the violaiton")
    confidence:Optional[int] = Field(None, description="LLM confidence on the violation")

class ComplianceReport(BaseModel):
    query :str = Field(...,description="Original user query / analyzed secenario")
    summary:str = Field(...,description="High Level summary of the findings and risk assesments")
    findings:List[ViolationFindings] =Field(..., description="List of detected violations")
    overall_severity:Optional[str] =Field(None, description="Aggregated severity level across all findings")
    generated_at:Optional[str] = Field(None, "Timestamp of report generation")
